# Generated by Django 6.0 on 2025-12-09 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cargo', models.CharField(default='Funcionário', max_length=50)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_admissao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('salario_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irrf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_extras_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('faltas_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qtd_horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('qtd_faltas', models.IntegerField(default=0)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
            ],
        ),
    ]
