# Generated by Django 6.0 on 2025-12-09 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='folhapagamento',
            old_name='faltas_valor',
            new_name='bonus',
        ),
        migrations.RenameField(
            model_name='folhapagamento',
            old_name='horas_extras_valor',
            new_name='deducoes_manuais',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cpf',
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='valor_faltas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='valor_horas_extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='mes_referencia',
            field=models.CharField(max_length=7),
        ),
    ]
