# Generated by Django 4.2.26 on 2025-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=14, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Telefone', models.CharField(max_length=15)),
                ('Data_de_nascimento', models.DateField()),
                ('RG', models.CharField(max_length=12, unique=True)),
                ('Endereco', models.CharField(max_length=200)),
                ('Bairro', models.CharField(max_length=100)),
            ],
        ),
    ]
